### ISSUE TITLE
在popup使用崩溃。

### ISSUE THREAD

**Issue by candebbs** [SValence/SafeKeyboard#3]
在popwindow使用，点击数字键和功能键没有问题，点击字母键和符号键会崩的，报错信息如下：
```
Unable to add window -- token android.view.ViewRootImpl$W@3b8b6b8 is not valid; is your activity running?
    android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@3b8b6b8 is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:579)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
        at android.widget.PopupWindow.invokePopup(PopupWindow.java:1315)
        at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1075)
        at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1038)
        at android.inputmethodservice.KeyboardView.showKey(KeyboardView.java:972)
        at android.inputmethodservice.KeyboardView.access$100(KeyboardView.java:70)
        at android.inputmethodservice.KeyboardView$1.handleMessage(KeyboardView.java:261)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
```

**Comment by SValence** [comment]
查看 KeyboardView 的源码可以看到，预览 preview 的显示是通过 PopupWindow 来完成的，在 Android里是不可以在 PopopWindow 中弹出另外一个 PopupWindow 的，在代码中关闭显示预览即可正常使用。所以这里如果需要在 PopupWindow 中显示 SafeKeyboard 预览界面，需要另寻他法。
