### ISSUE TITLE
设置keyPreviewLayout导致App崩溃

### ISSUE THREAD

**Issue by fishsoft** [SValence/SafeKeyboard#6]
设置keyPreviewLayout属性之后，app直接崩溃，想要预览按下你的key，有什么好的解决方案没？

**Comment by SValence** [comment]
看下报什么错误吧。我还没有遇到过这种问题。可能是预览布局文件有问题。
你如果找不到问题的话，就把错误日志附上来。我来看下
不过我可能不能及时回复，最近在忙其他的事情。望理解

**Comment by fishsoft** [comment]
`2019-08-01 08:59:58.574 18148-18148/com.morse.safekeyboard E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.morse.safekeyboard, PID: 18148
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.setState(int[])' on a null object reference
        at android.inputmethodservice.KeyboardView.showKey(KeyboardView.java:968)
        at android.inputmethodservice.KeyboardView.access$100(KeyboardView.java:75)
        at android.inputmethodservice.KeyboardView$1.handleMessage(KeyboardView.java:382)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7046)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)`

**Comment by fishsoft** [comment]
不好意思，是图片图文，从github上下载下来的图片文件损坏了，导致加载不出来
